---
- hosts: dev
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Install docker-py Python module
      pip:
        name: docker-py
        state: present

    - name: Start the container
      docker_container:
        name: krish
        image: "mkvm2050/krish4:1.2"
        state: started
        published_ports:
          - "0.0.0.0:8082:8082"
