---
- hosts: dev
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: hariapp
        image:  "mkvm2050/krish4:1.2"
        state: started
        published_ports:
          - 0.0.0.0:8083:8083
